#!/bin/bash

MOUNTS=""

if [[ -f ~/.mw ]]
then
    MOUNTS+="  "
fi

if [[ -f ~/.cl ]]
then
    MOUNTS+="[c]"
fi

if [[ -f ~/.dfl ]]
then
    MOUNTS+="[df]"
fi

if [[ -f ~/.spl ]]
then
    MOUNTS+="[sp]"
fi

if [[ -f ~/.dcl ]]
then
    MOUNTS+="[dc]"
fi

if [[ -f ~/.kl ]]
then
    MOUNTS+="[kp]"
fi

if [[ -f ~/.rl ]]
then
    MOUNTS+="[rl]"
fi

echo "$MOUNTS"
