#!/bin/bash

MAX_LENGTH=48

__get_name()
{
    NAME=$(mpc | head -1)
    NAME=${NAME#\.*}

    if [ ${#NAME} -gt 48 ]
    then
        NAME=$(echo $NAME | cut --complement -c48-)
        NAME+='...'
    fi
    echo "$NAME"
}

__main()
{
    PLAY='♪'
    PAUSE=''
    MPCST=$(mpc | awk '/\[(playing||paused)\]/{print $1}')

    case $MPCST in
        '[playing]')
            echo "$PLAY $(__get_name)  "
            ;;
        '[paused]')
            echo "$PAUSE  $(__get_name)  "
            ;;
        *)
            ;;
    esac
}

__main

unset -f __get_name
unset -f __main
